shiro:
  promiss:
    anon:
      - /security-user/login
      - /static/**
      - /doc.html
      - /doc.html/**
      - /swagger-resources/**
      - /v2/api-docs/**
      - /webjars/**
      - /configuration/security
      - /configuration/ui
      - /swagger-resources/configuration/ui/**
      - /swagger-resources/configuration/security/**
    authc:
      - /testThymeleaf
      - /**
    user:
    perms:
    role:
    logurl: /doc.html
    sucessurl: /index
    error: /error